# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-05 08:44
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name=b'T\xc3\xadtulo')),
                ('description', models.TextField(verbose_name=b'Descripci\xc3\xb3n')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Fecha de creaci\xc3\xb3n')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Fecha de publicaci\xc3\xb3n')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name=b'Nombre')),
                ('email', models.CharField(max_length=100, verbose_name=b'Correo electr\xc3\xb3nico')),
                ('message', models.TextField(verbose_name=b'Mensaje')),
                ('received_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Recibido')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name=b'Nombre')),
                ('description', models.CharField(max_length=250, verbose_name=b'Descripci\xc3\xb3n')),
                ('url', models.CharField(max_length=150, verbose_name=b'M\xc3\xa1s informaci\xc3\xb3n')),
                ('logotype', models.CharField(max_length=200, verbose_name=b'Logotipo')),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10000000)], verbose_name=b'Precio')),
                ('celebrate_data', models.DateTimeField(verbose_name=b'Fecha y Hora')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Fecha publicaci\xc3\xb3n')),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150)),
                ('free', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Fecha publicaci\xc3\xb3n')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(default=b'', max_length=200)),
                ('img', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('add_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
            ],
        ),
        migrations.CreateModel(
            name='FriendType',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('add_data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('region_eus', models.CharField(max_length=100)),
                ('longitude', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(-100000), django.core.validators.MaxValueValidator(10000000)], verbose_name=b'Longitud')),
                ('latitude', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(-1000000), django.core.validators.MaxValueValidator(10000000)], verbose_name=b'Latitud')),
                ('region_ca', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name=b'T\xc3\xadtulo')),
                ('description', models.CharField(max_length=200, verbose_name=b'Descripci\xc3\xb3n')),
                ('text', ckeditor.fields.RichTextField(verbose_name=b'Contenido')),
                ('source', models.CharField(max_length=250, verbose_name=b'Fuente')),
                ('source_title', models.CharField(max_length=200, verbose_name=b'T\xc3\xadtulo fuente')),
                ('the_most_important', models.BooleanField(default=False, verbose_name=b'\xc2\xbfDestacado?')),
                ('active', models.BooleanField(default=True, verbose_name=b'\xc2\xbfActivo?')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Fecha de creaci\xc3\xb3n')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Fecha de publicaci\xc3\xb3n')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category1', to='blog.Category')),
                ('category2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category2', to='blog.Category')),
            ],
        ),
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name=b'Nombre')),
                ('description', ckeditor.fields.RichTextField(verbose_name=b'Descripci\xc3\xb3n')),
                ('active', models.BooleanField(default=False, verbose_name=b'\xc2\xbfActivo?')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Fecha de creaci\xc3\xb3n')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Fecha de publicaci\xc3\xb3n')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name=b'Nombre')),
                ('intro', models.CharField(max_length=200, verbose_name=b'Introducci\xc3\xb3n')),
                ('description', ckeditor.fields.RichTextField(verbose_name=b'Descripci\xc3\xb3n')),
                ('source', models.CharField(max_length=250, verbose_name=b'Fuente')),
                ('source_title', models.CharField(max_length=200, verbose_name=b'T\xc3\xadtulo de la fuente')),
                ('photo_url', models.CharField(max_length=255, verbose_name=b'Imagen')),
                ('finish', models.BooleanField(default=False, verbose_name=b'\xc2\xbfFinalizado')),
                ('active', models.BooleanField(default=True, verbose_name=b'\xc2\xbfActivo?')),
                ('start_project_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Fecha de inicio')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Fecha de publicaci\xc3\xb3n')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.PostType'),
        ),
        migrations.AddField(
            model_name='friend',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.FriendType'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ForeignKey(default=b'Carrera', on_delete=django.db.models.deletion.CASCADE, related_name='Tipo', to='blog.EventType'),
        ),
    ]
