# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-30 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160630_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendtype',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posttype',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='friendtype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='posttype',
            name='name',
            field=models.CharField(max_length=100, verbose_name=b'Nombre'),
        ),
    ]
