# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-04 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Herria',
            fields=[
                ('herri_kodea', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Code')),
                ('izena', models.CharField(max_length=50, verbose_name='Name')),
                ('probintzia', models.CharField(max_length=50, verbose_name='Province')),
                ('autonomi_erkidegoa', models.CharField(max_length=100, verbose_name='Autonomy (ES)')),
                ('autonomi_erkidegoa_eus', models.CharField(max_length=100, verbose_name='Autonomy (EU)')),
                ('longitudea', models.CharField(max_length=15, verbose_name='Longitude')),
                ('latitudea', models.CharField(max_length=15, verbose_name='Latitude')),
                ('autonomi_erkidegoa_ca', models.CharField(max_length=100, verbose_name='Autonomy (CA)')),
            ],
        ),
        migrations.CreateModel(
            name='Lasterketa',
            fields=[
                ('laster_kodea', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Code')),
                ('izena', models.CharField(max_length=256, verbose_name='Name')),
                ('edizio_kop', models.IntegerField(verbose_name='Edition')),
                ('distantzia', models.CharField(max_length=6, verbose_name='Distance')),
                ('desnibela', models.CharField(max_length=5, verbose_name='Climb')),
                ('longitudea', models.CharField(max_length=15, verbose_name='Longitude')),
                ('latitudea', models.CharField(max_length=15, verbose_name='Latitude')),
                ('route', models.CharField(max_length=20, verbose_name='Route ID')),
                ('route_source', models.CharField(max_length=30, verbose_name='Route Source')),
                ('noiz', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('start_time', models.TimeField(default=django.utils.timezone.now, verbose_name='Start Time')),
                ('web', models.CharField(max_length=256, verbose_name='Web')),
                ('video', models.BooleanField(default=False, verbose_name='Video')),
                ('mota', models.CharField(max_length=50, verbose_name='Type')),
                ('gehitua', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Add Data')),
                ('circle_circuit', models.BooleanField(default=True, verbose_name='Circle circuit?')),
                ('finish_longitudea', models.CharField(max_length=15, verbose_name='Finish Longitude')),
                ('finish_latitudea', models.CharField(max_length=15, verbose_name='Finish Latitude')),
                ('short_url', models.CharField(max_length=100, verbose_name='Short URL')),
                ('finish_herri_kodea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='town_finish', to='servirace.Herria')),
                ('herri_kodea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='town', to='servirace.Herria')),
            ],
        ),
        migrations.CreateModel(
            name='Organizator',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('tlf', models.CharField(max_length=30, verbose_name='Telephone 1')),
                ('tlf2', models.CharField(max_length=30, verbose_name='Telephone 2')),
                ('twitter', models.CharField(max_length=50, verbose_name='Twitter')),
                ('facebook', models.CharField(max_length=150, verbose_name='Facebook')),
                ('email', models.CharField(max_length=256, verbose_name='E-Mail')),
            ],
        ),
        migrations.AddField(
            model_name='lasterketa',
            name='organizator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servirace.Organizator'),
        ),
    ]
